---
- name: Add tower team
  awx.awx.tower_team:
    name: "{{ item.my_team }}"
    organization: "{{ my_organization }}"
    state: present
  loop: "{{ my_users }}"
  when: my_users | length > 0

- name: Add Git Project
  awx.awx.tower_project:
    name: "{{ item.my_project }}"
    organization: "{{ my_organization }}"
    state: present
    scm_type: git
    scm_url: "{{ item.my_git }}"
  loop: "{{ projects }}"

- name: Add user to the member role of team
  awx.awx.tower_role:
    user: "{{ item.my_name }}"
    target_team: "{{ item.my_team }}"
    role: member
    state: present
  loop: "{{ my_users }}"
  when: my_users | length > 0
