---
- name: Add Job Template
  awx.awx.tower_job_template:
    name: "{{ item.my_job_template }}"
    job_type: "run"
    organization: "{{ my_organization }}"
    inventory: "{{ item.my_inventory }}"
    project: "{{ item.my_project }}"
    playbook: "{{ item.my_playbook }}"
    credential: "{{ item.my_credential }}"
    survey_enabled: "{{ item.my_survey_enabled | default(omit) }}"
  loop: "{{ my_jobs }}"

- name: Add role to current team
  awx.awx.tower_role:
    team: "{{ item.0.my_team }}"
    role: execute
    job_templates: "{{ item.1.my_job_template }}"
    state: present
  loop: "{{ my_users | product(my_jobs) }}"
  when: my_users | length > 0
