---
- name: Add Credential (Machine)
  awx.awx.tower_credential:
    name: "{{ item.my_credential }}"
    credential_type: Machine
    state: present
    organization: "{{ my_organization }}"
    update_secrets: true
    tower_oauthtoken: "{{ my_token }}"
    inputs:
      username: "{{ item.my_login_name }}"
      password: "{{ item.my_password ) }}"
    loop: "{{ credentials }}"
    loop_control:
      extended: yes
    when: credentials[ ansible_loop.index0 ].my_type == "Machine"

- name: Add Credential (Git)
  awx.awx.tower_credential:
    name: "{{ item.my_credential }}"
    credential_type: "Source Control"
    state: present
    organization: "{{ my_organization }}"
    update_secrets: true
    tower_oauthtoken: "{{ my_token }}"
    inputs:
      username: "git"
      ssh_key_data: "{{ lookup('file', item.my_secret ) }}"
    loop: "{{ credentials }}"
    loop_control:
      extended: yes
    when: credentials[ ansible_loop.index0 ].my_type == "Git"
